### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'pastes/<username>'

### ISSUE THREAD

**Issue by 11ph22il** [bbbbbrie/pastebin-bisque#13]
Hey, I was trying to download an user's pastebin pastes using this script, but It always throws this error:

Pastebin username: https://pastebin.com/u/Zaglebiak
```
d:\User\Documents\GitTest\pastebin-bisque>python main.py -u Zaglebiak -z
2023-07-02 21:30:39.337 | INFO     | __main__:main:187 - PASTEBIN USER SELECTED: Zaglebiak
2023-07-02 21:30:39.340 | INFO     | __main__:count_download_all_pastes:144 - https://pastebin.com/u/Zaglebiak
2023-07-02 21:30:40.126 | DEBUG    | __main__:count_all_pages:103 - We got through it.
2023-07-02 21:30:40.129 | DEBUG    | __main__:count_download_all_pastes:149 - TARGET ANALYZED: Zaglebiak has -1 pages of pastes.
2023-07-02 21:30:40.131 | SUCCESS  | __main__:main:191 - I downloaded 0 pastes.
2023-07-02 21:30:40.133 | INFO     | __main__:main:193 - You want to zip.
Traceback (most recent call last):
  File "d:\User\Documents\GitTest\pastebin-bisque\main.py", line 211, in <module>
    main(the_target, to_zip)
  File "d:\User\Documents\GitTest\pastebin-bisque\main.py", line 194, in main
    zip_the_pastes(the_target)
  File "d:\User\Documents\GitTest\pastebin-bisque\main.py", line 178, in zip_the_pastes
    shutil.make_archive(output_filename, 'zip', dir_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 1053, in make_archive
    os.chdir(root_dir)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'pastes/Zaglebiak'
``` 

Folder permissions:

![image](https://github.com/bbbbbrie/pastebin-bisque/assets/166390/1eae9861-f17b-4b15-b63f-7777efc40ca8)

**Comment by bbbbbrie** [comment]
:wave: Hi @11ph22il ! Thanks for taking the time to open this :bug:  issue! 

First, I will tell you: I did not test this at all on Windows. :sweat: 

On line 69 of `main.py`, I [note](https://github.com/bbbbbrie/pastebin-bisque/blob/main/main.py#L69) that I am doing the Python equivalent of `mkdir -p`.  You can see that a few lines later in:

```
    the_path = "pastes/" + the_target
    if not os.path.exists(the_path):
        os.makedirs(the_path)
```

I would _guess_ that Python on Windows handles this a bit differently. 

## :feet:  Next Steps

I think that using `os.path.isdir(the_path)` instead of `os.path.exists(the_path)` might be a good approach. 

:tada: From a quick test, `os.path.exists` still works on Linux. I'll test this a bit further and then see about a PR to fix this up. 

Thanks again!

--
:unicorn:  Brie
